### ISSUE TITLE
Add contribution.md

### ISSUE THREAD

**Issue by D3v3sh5ingh** [D3v3sh5ingh/Graph-Theory-Algorithms#12]

**Comment by satyabansahoo2000** [comment]
@D3v3sh5ingh I would like to work on this.

**Comment by D3v3sh5ingh** [comment]
Awesome! Assigning.

**Comment by satyabansahoo2000** [comment]
[added CONTRIBUTION.MD #14 ](https://github.com/D3v3sh5ingh/Graph-Theory-Algorithms/pull/14)
