### ISSUE TITLE
Add well documented readme to show all algos list.

### ISSUE THREAD

**Issue by D3v3sh5ingh** [D3v3sh5ingh/Graph-Theory-Algorithms#6]

**Comment by hnishal** [comment]
@D3v3sh5ingh assign me this issue and tell me what all you wan in the read me

**Comment by D3v3sh5ingh** [comment]
@hnishal Assigned!
You can add a bulleted list with all the algorithms (with links to respective files) we have in the repository.

**Comment by hnishal** [comment]
ohkay im on it

**Comment by D3v3sh5ingh** [comment]
Resolved by #8 
Closing..
